spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/verified-access
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: user
    password: pwd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          trust: "*"
application:
    name: VerifiedAccess
server:
  port: 8085
